use crate::diagnostic::Span;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenKind {
    Fn,
    Let,
    Mut,
    Const,
    Static,
    Ret,
    If,
    Else,
    Loop,
    While,
    Break,
    Continue,
    Use,
    Module,
    Package,
    Version,
    Type,
    Target,
    Runtime,
    Entry,
    Requires,
    Dep,
    End,
    Unsafe,
    Extern,
    Asm,
    True,
    False,
    And,
    Or,
    Not,
    Ident,
    IntLit,
    StrLit,
    ByteLit,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Eq,
    EqEq,
    BangEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    Arrow,
    LParen,
    RParen,
    LBracket,
    RBracket,
    Comma,
    Dot,
    Colon,
    Newline,
    Eof,
    Error,
    Comment,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: String,
    pub span: Span,
}

impl Token {
    pub fn new(kind: TokenKind, lexeme: String, span: Span) -> Self {
        Self { kind, lexeme, span }
    }
}

pub fn keyword_kind(text: &str) -> Option<TokenKind> {
    Some(match text {
        "fn" => TokenKind::Fn,
        "let" => TokenKind::Let,
        "mut" => TokenKind::Mut,
        "const" => TokenKind::Const,
        "static" => TokenKind::Static,
        "ret" => TokenKind::Ret,
        "if" => TokenKind::If,
        "else" => TokenKind::Else,
        "loop" => TokenKind::Loop,
        "while" => TokenKind::While,
        "break" => TokenKind::Break,
        "continue" => TokenKind::Continue,
        "use" => TokenKind::Use,
        "module" => TokenKind::Module,
        "package" => TokenKind::Package,
        "version" => TokenKind::Version,
        "type" => TokenKind::Type,
        "target" => TokenKind::Target,
        "runtime" => TokenKind::Runtime,
        "entry" => TokenKind::Entry,
        "requires" => TokenKind::Requires,
        "dep" => TokenKind::Dep,
        "end" => TokenKind::End,
        "unsafe" => TokenKind::Unsafe,
        "extern" => TokenKind::Extern,
        "asm" => TokenKind::Asm,
        "true" => TokenKind::True,
        "false" => TokenKind::False,
        "and" => TokenKind::And,
        "or" => TokenKind::Or,
        "not" => TokenKind::Not,
        _ => return None,
    })
}

