%define AST_NONE 0
%define AST_SOURCE_FILE 1
%define AST_USE_DECL 2
%define AST_FN_DECL 3
%define AST_BLOCK 4
%define AST_RET_STMT 5
%define AST_CALL_STMT 6
%define AST_INT_LIT 7
%define AST_STR_LIT 8
%define AST_IDENT 9
%define AST_PATH 10
%define AST_ERROR 11

%define AST_CAP 1024
%define AST_KIND 0
%define AST_SPAN_START 8
%define AST_SPAN_END 16
%define AST_CHILD_OR_DATA 24
%define AST_NEXT_OR_EXTRA 32
%define AST_SIZE 40

