%define TOK_EOF 0
%define TOK_IDENT 1
%define TOK_INT 2
%define TOK_STRING 3
%define TOK_ERROR 4

%define TOK_USE 10
%define TOK_FN 11
%define TOK_RET 12
%define TOK_END 13
%define TOK_TRUE 14
%define TOK_FALSE 15

%define TOK_ARROW 30
%define TOK_DOT 31
%define TOK_SLASH 32
%define TOK_COMMA 33
%define TOK_EQ 34
%define TOK_NEWLINE 40

%define TOKEN_CAP 4096
%define TOKEN_TYPE 0
%define TOKEN_START 8
%define TOKEN_LEN 16
%define TOKEN_LINE 24
%define TOKEN_COL 32
%define TOKEN_PAYLOAD 40
%define TOKEN_SIZE 48

