SourceFile
    = (Newline | Comment | Item)* EOF ;

Item
    = UseDecl
    | FnDecl ;

UseDecl
    = "use" Path Newline* ;

FnDecl
    = UnsafeOpt "fn" Ident ParamList "->" TypeName Newline* Block "end" ;

UnsafeOpt
    = "unsafe" | empty ;

ParamList
    = (Ident TypeName)* ;

Block
    = Statement* ;

Statement
    = LetDecl
    | MutDecl
    | AssignStmt
    | RetStmt
    | IfStmt
    | LoopStmt
    | WhileStmt
    | BreakStmt
    | ContinueStmt
    | UnsafeBlock
    | ExprStmt ;

LetDecl
    = "let" Ident TypeName "=" Expr Newline* ;

MutDecl
    = "mut" Ident TypeName "=" Expr Newline* ;

AssignStmt
    = Ident "=" Expr Newline* ;

RetStmt
    = "ret" Expr? Newline* ;

IfStmt
    = "if" Expr "->" Newline* Block ElseOpt "end" ;

ElseOpt
    = "else" "->" Newline* Block | empty ;

LoopStmt
    = "loop" "->" Newline* Block "end" ;

WhileStmt
    = "while" Expr "->" Newline* Block "end" ;

BreakStmt
    = "break" Newline* ;

ContinueStmt
    = "continue" Newline* ;

UnsafeBlock
    = "unsafe" "->" Newline* Block "end" ;

ExprStmt
    = Expr Newline* ;

Expr
    = PrattExpression ;

Pratt precedence, high to low:

1. command-style function call
2. unary `not`, unary `-`
3. `*`, `/`, `%`
4. `+`, `-`
5. `<`, `<=`, `>`, `>=`
6. `==`, `!=`
7. `and`
8. `or`

Primary
    = IntLit
    | StrLit
    | "true"
    | "false"
    | Path
    | "(" Expr ")" ;

Path
    = Ident ("/" Ident | "." Ident)* ;

TypeName
    = Ident | "*" Ident ;

PackageFile
    = PackageField VersionField TypeField TargetField RuntimeField PackageLine* "end" ;

PackageLine
    = EntryField | RequiresField | DepField | PanicField | BudgetField | LinkField ;

PackageField
    = "package" Ident ;

VersionField
    = "version" SemVer ;

TypeField
    = "type" ("executable" | "library" | "build-script") ;

TargetField
    = "target" ("linux-x86_64" | "host") ;

RuntimeField
    = "runtime" ("tiny" | "none") ;

